### ISSUE TITLE
Process has died error

### ISSUE THREAD

**Issue by Harshill09** [ARK-Electronics/ROS2_PX4_Offboard_Example#11]
Tried running the launch file but the logging terminal shows the process has died error:

```~/px4_ros2_ws$ ros2 launch px4_offboard offboard_velocity_control.launch.py
[INFO] [launch]: All log files can be found below /home/USERNAME/.ros/log/2023-09-04-19-45-35-649660-USERNAME-22502
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [visualizer-1]: process started with pid [22503]
[INFO] [gnome-terminal-2]: process started with pid [22505]
[INFO] [gnome-terminal-3]: process started with pid [22507]
[INFO] [velocity_control-4]: process started with pid [22509]
[INFO] [rviz2-5]: process started with pid [22511]
[INFO] [gnome-terminal-2]: process has finished cleanly [pid 22505]
[rviz2-5] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[INFO] [gnome-terminal-3]: process has finished cleanly [pid 22507]
[visualizer-1] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT is deprecated. Use ReliabilityPolicy.BEST_EFFORT instead.
[visualizer-1]   warnings.warn(
[visualizer-1] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST is deprecated. Use HistoryPolicy.KEEP_LAST instead.
[visualizer-1]   warnings.warn(
[velocity_control-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT is deprecated. Use ReliabilityPolicy.BEST_EFFORT instead.
[velocity_control-4]   warnings.warn(
[velocity_control-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[velocity_control-4]   warnings.warn(
[velocity_control-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST is deprecated. Use HistoryPolicy.KEEP_LAST instead.
[velocity_control-4]   warnings.warn(
[velocity_control-4] Traceback (most recent call last):
[velocity_control-4]   File "/home/USERNAME/px4_ros2_ws/install/px4_offboard/lib/px4_offboard/velocity_control", line 33, in <module>
[velocity_control-4]     sys.exit(load_entry_point('px4-offboard==0.0.0', 'console_scripts', 'velocity_control')())
[velocity_control-4]   File "/home/USERNAME/px4_ros2_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/velocity_control.py", line 309, in main
[velocity_control-4]     offboard_control = OffboardControl()
[velocity_control-4]   File "/home/USERNAME/px4_ros2_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/velocity_control.py", line 110, in __init__
[velocity_control-4]     self.arm_state = VehicleStatus.ARMING_STATE_MAX
[velocity_control-4] AttributeError: type object 'VehicleStatus' has no attribute 'ARMING_STATE_MAX'. Did you mean: 'ARMING_STATE_ARMED'?
[rviz2-5] [INFO] [1693836936.665989450] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1693836936.666187427] [rviz2]: OpenGl version: 4.5 (GLSL 4.5)
[ERROR] [velocity_control-4]: process has died [pid 22509, exit code 1, cmd '/home/USERNAME/px4_ros2_ws/install/px4_offboard/lib/px4_offboard/velocity_control --ros-args -r __node:=velocity -r __ns:=/px4_offboard'].
[rviz2-5] [INFO] [1693836936.765787542] [rviz2]: Stereo is NOT SUPPORTED
```

The simulation is running, every node is running but the simulation is not entering offboard mode (hovering) when armed (pressing the space key). 

I'm using Ubuntu 22.04, Python 3.10.12, ROS2 Humble and all the other default supported dependencies and environment.

**Comment by adrienJeg** [comment]
Hi, I'm having the same issue

**Comment by adrienJeg** [comment]
Ok, this commit 9192cecdaf6bb690591f3a58ac66c8db2dff0c41 solved the issue !
