### ISSUE TITLE
Having issue while buuilding the workspace

### ISSUE THREAD

**Issue by ckjunaid** [ARK-Electronics/ROS2_PX4_Offboard_Example#20]

**Comment by ckjunaid** [comment]
colcon build
Starting >>> px4_msgs
--- stderr: px4_msgs                         
CMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name px4_msgs
  --arguments-file
  /home/junaid/junu_ws/build/px4_msgs/rosidl_adapter__arguments__px4_msgs.json
  --output-dir /home/junaid/junu_ws/build/px4_msgs/rosidl_adapter/px4_msgs
  --output-file
  /home/junaid/junu_ws/build/px4_msgs/rosidl_adapter/px4_msgs.idls) returned
  error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 51, in evaluate_template
      em.BUFFERED_OPT: True,

  AttributeError: module 'em' has no attribute 'BUFFERED_OPT'

  

  During handling of the above exception, another exception occurred:

  

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:28 (rosidl_generate_interfaces)


---
Failed   <<< px4_msgs [0.93s, exited with code 1]

Summary: 0 packages finished [1.06s]
  1 package failed: px4_msgs
  1 package had stderr output: px4_msgs

this is the error while building the workspace

**Comment by Rodney-yah** [comment]
Thanks you for your solution. Anyboy who met this error should check this guy's page.

**Comment by ckjunaid** [comment]
> Thanks you for your solution. Anyboy who met this error should check this guy's page.

Please message when you complete the teleop.

**Comment by returncode13** [comment]
what is the solution to this?

**Comment by returncode13** [comment]
ok downgraded empy from 4.* to 3.3.4 and now px4 msgs is been correctly build by colcon 
See (https://github.com/ckjunaid/error-in-px4_msgs)  Thanks @ckjunaid
